apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: jenkins
          image: kittisakbook/jenkins:2.554-jdk21
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkinsdata
            - mountPath: /var/run/docker.sock  # เพิ่ม
              name: docker-sock
      volumes:
        - name: jenkinsdata
          persistentVolumeClaim:
            claimName: jenkins-volume-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock