apiVersion: v1
kind: PersistentVolume
metadata:
  name: jbpt-jenkins-volume
  labels:
    type: local
    app: jenkins-jbpt
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.1
    path: /srv/nfs/jenkins