global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'prometheus' # Prometheus self-scraping configuration

    static_configs:
      - targets:
          - 'localhost:9090'

        labels:
          role: 'monitoring'
          node: 'prometheus-server'

  - job_name: 'k8s-control-node' # Kubernetes Control Plane
    static_configs:
      - targets:
          - '192.168.193.101:9100'

        labels:
          role: 'control-plane'
          node: 'control-1'

  - job_name: 'k8s-worker-nodes' # Kubernetes Worker Nodes
    static_configs:
      - targets:
          - '192.168.193.102:9100'

        labels:
          role: 'worker'
          node: 'worker-1'

      - targets:
          - '192.168.193.103:9100'

        labels:
          role: 'worker'
          node: 'worker-2'

      - targets:
          - '192.168.193.104:9100'

        labels:
          role: 'worker'
          node: 'worker-3'

  - job_name: 'jbpt-backend'
    static_configs:
      - targets:
          - '192.168.193.104:30081'   # NodePort ของ backend (IP ไหนก็ได้)
        labels:
          role: 'app'
          service: 'backend'