[control_plane]
node1 ansible_host=192.168.193.101 ansible_user=node01

[workers]
node2 ansible_host=192.168.193.102 ansible_user=node02
node3 ansible_host=192.168.193.103 ansible_user=node03
node4 ansible_host=192.168.193.104 ansible_user=node04

[cluster:children]
control_plane
workers

[cluster:vars]
ansible_connection=ssh
ansible_password=admin
ansible_become=true
ansible_become_password=admin
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3